name: Deploy Next.js to EC2

on:
  push:
    branches:
      - develop

jobs:
  # 빌드 및 배포
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build
        env:
          NODE_ENV: 'development'
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
          KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          TEST_KAKAO_ID: ${{ secrets.TEST_KAKAO_ID }}
          TEST_KAKAO_PHONE: ${{ secrets.TEST_KAKAO_PHONE }}
          SUBWAY_API_KEY_0: ${{ secrets.SUBWAY_API_KEY_0 }}
          SUBWAY_API_KEY_1: ${{ secrets.SUBWAY_API_KEY_1 }}
          SUBWAY_API_KEY_2: ${{ secrets.SUBWAY_API_KEY_2 }}
          SEOUL_API_KEY: ${{ secrets.SEOUL_API_KEY }}
          NEXT_PUBLIC_KAKAO_MAP_KEY: ${{ secrets.NEXT_PUBLIC_KAKAO_MAP_KEY }}
          NEXT_PUBLIC_TMAP_KEY: ${{ secrets.NEXT_PUBLIC_TMAP_KEY }}
          DATA_GO_KR_API_KEY_0: ${{ secrets.DATA_GO_KR_API_KEY_0 }}
          DATA_GO_KR_API_KEY_1: ${{ secrets.DATA_GO_KR_API_KEY_1 }}
          DATA_GO_KR_API_KEY_2: ${{ secrets.DATA_GO_KR_API_KEY_2 }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            100hailey/nextjs-app:latest
            100hailey/nextjs-app:${{ github.sha }}

  # EC2 배포
  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            docker pull 100hailey/nextjs-app:latest
            docker stop nextjs-app || true
            docker rm nextjs-app || true
            docker run -d \
              -p 3000:3000 \
              --name nextjs-app \
              -e NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
              --restart unless-stopped \
              100hailey/nextjs-app:latest
